kind: pipeline
name: Smart Home Build Pipeline
type: docker
steps:
  - name: compile
    image: python:3.8.0-slim
    commands:
      - pip install --upgrade pip setuptools nose
      - pip install --no-index -r requirements.txt
      - python setup.py install
      - nosetests tests
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: github-drone-builds
      username: drone
    when:
      status: [ success, failure ]