pipeline:
  build:
    image: python:3.8.0-slim
    commands:
      - pip install --upgrade pip setuptools
      - pip install --no-index -r requirements.txt
      - pip install --no-index -r test-requirements.txt
      - python setup.py install