kind: pipeline
name: Smart Home Build Pipeline
type: docker
steps:
  - name: compile
    image: python:3.8.0-slim
    commands:
      - pip install --upgrade pip setuptools
      - pip install --no-index -r requirements.txt
      - python setup.py install
    when:
      branch:
        - master
      event:
        - push
        - pull-request