kind: pipeline
name: Smart Home Build Pipeline
type: docker
steps:
  - name: compile
    image: python:3.8.0-slim
    commands:
      - pip install --upgrade pip setuptools
      - pip install --no-index -r requirements.txt
      - python setup.py install
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: lint
    image: python:3.8.0-slim
    commands:
      - pip install --upgrade pip pylint
      - pylint tasks
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: run tox
    image: python:3.8.0-slim
    commands:
      - pip install --upgrade pip tox
      - tox
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: run tests
    image: python:3.8.0-slim
    commands:
      - pip install --upgrade pip nose
      - nosetests tests
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: jorgeacf/smart-home
      dockerfile: docker/Dockerfile
      tags:
        - latest
        - '1.0.1'
        - '1.0'

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: github-drone-builds
      username: drone
    when:
      status: [ success, failure ]