FROM arm32v6/python:3.8-rc-alpine

# Create app directory
RUN mkdir /app
WORKDIR /app

# Bundle app source
COPY . /app

RUN apk update && apk add nmap

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "python", "tasks" ]